[versions]
junit-version = "5.14.2"
okhttp = "4.9.2"
java-jwt = "3.18.2"
jackson = "2.11.0"
spring-boot = "2.3.12.RELEASE"
swagger-annotations = "1.6.3"
spring-boot-validation = "2.5.6"
swagger-codegen = "2.4.50"
swagger-generator = "2.19.2"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-version" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
spring-boot-starter-websocket = { module = "org.springframework.boot:spring-boot-starter-websocket", version.ref = "spring-boot" }
swagger-annotations = { module = "io.swagger:swagger-annotations", version.ref = "swagger-annotations" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "spring-boot-validation" }
swagger-codegen-cli = { module = "io.swagger:swagger-codegen-cli", version.ref = "swagger-codegen" }

[plugins]
swagger-generator = { id = "org.hidetake.swagger.generator", version.ref = "swagger-generator" }

[bundles]
junit-api = ["junit-jupiter-api"]
junit-runtime = ["junit-launcher", "junit-jupiter-engine"]
